### ISSUE TITLE
View вместо Image

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#10]
Можно ли сделать вместо image передавать компонент реакт

**Comment by ownikss** [comment]
Эта задача есть в беклоге. У карт вроде есть подобное апи, но пока оно не проверено. Постараюсь изучить вопрос, но после решения более приоритетных задач
Вероятно это будет реализовано, но не думаю что раньше 8 января

**Comment by Azshar** [comment]
Хорошо

**Comment by ownikss** [comment]
Обновлено в [версии 1.0.7](https://github.com/volga-volga/react-native-yamap/releases/tag/v1.0.7)
Пример использования:

```
<MapView>
  <Marker point={{ lat: 10, lon: 10 }}>
    <View style={{ width: 20, height: 20, background: 'red' }}/>
  </Marker>
</MapView>
```

Но функционал достаточно ограничен - не получится использовать компоненты с взаимодействием - инпуты, кнопки и подобное. Компонент переводится в картинку и отображается на карте. Касаемо производительности отсюда тоже могут быть проблемы. В целом рекомендую использовать данный функционал только в случае необходимости
