### ISSUE TITLE
iOS. рендеринг Marker с children крашит приложение

### ISSUE THREAD

**Issue by DazzlingFame** [volga-volga/react-native-yamap#100]
"react-native": "0.65.1"

Пытаюсь сделать `Marker` с иконкой и текстовым бабблом сбоку, но при помещении какого-либо компонента в 
`<Marker>...</Marker>` iOS приложение крашится

Пробую класть вот такое
```
<YaMap
    <Marker point={{lat: pin.coordinates.lat, lon: pin.coordinates.lon}} onPress={handlePinPress} >
      <View/>
    </Marker>
</YaMap>
```
От контента работоспособность не зависит, падает с любыми чайлдами

Ошибка:

![image](https://user-images.githubusercontent.com/15292833/165771334-b76b51ab-5f89-4687-93be-3315f4f27a70.png)

**Comment by ownikss** [comment]
Какая версия библиотеки? Воспроизводится ли проблема если у children будет задан размер в стилях?

Например <View style={{width: 20, height: 20 }}/>

**Comment by DazzlingFame** [comment]
> Какая версия библиотеки? Воспроизводится ли проблема если у children будет задан размер в стилях?
> 
> Например <View style={{width: 20, height: 20 }}/>

`    "react-native-yamap": "4.0.3",`

Попробовал с стилями размера, это помогло. 

Пытался вспомнить кейс, когда мне мог понадобиться `children` для Marker'а без контента и без размера и так и не смог. В таком случае этот issue становится не актуален

![image](https://user-images.githubusercontent.com/15292833/166718252-fc0c0b18-8755-4a95-90a2-ac29770337b3.png)
