### ISSUE TITLE
this.refs.map.fitAllMarkers()

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#11]
Перестало работать после обновления до 1.0.5

**Comment by ownikss** [comment]
Проверил на обеих платформах - метод отрабатывает. Может какой то специфичный набор маркеров? Я проверял на простейших, например
```
[
     {lat: 50, lon: 50},
     {lat: 50, lon: 20},
     {lat: 20, lon: 20},
]
```
