### ISSUE TITLE
Добавить кластеризацию

### ISSUE THREAD

**Issue by eugnazaroff** [volga-volga/react-native-yamap#115]
Добавить кластеризацию, используя движок supercluster.

**Comment by azesmway** [comment]
В RNYMView.m можно добавить

```
@implementation RNYMView {
...
    YMKClusterizedPlacemarkCollection *collection;
}
```

```
- (instancetype)init {
...
    collection = [_map.mapWindow.map.mapObjects addClusterizedPlacemarkCollectionWithClusterListener:self];
}
```

и можно использовать родную кластеризацию

**Comment by ownikss** [comment]
Фича в работе. Планируем использовать нативные кластеры от яндекса. Пока не будет сильной кастомизации, в будущем доработаем
Планируем закончить на этой неделе

**Comment by eugnazaroff** [comment]
большое спасибо, будем тестировать!
