### ISSUE TITLE
Не выбирается нужный маркер Android #76

### ISSUE THREAD

**Issue by youngblader** [volga-volga/react-native-yamap#118]
Продублирую, https://github.com/volga-volga/react-native-yamap/issues/76

**Comment by nursakn** [comment]
Можно использовать дебаунс, для предотвращения вызова функции за короткий период.

**Comment by ownikss** [comment]
Дубль
https://github.com/volga-volga/react-native-yamap/issues/76

Обсуждение в исходной ветке
