### ISSUE TITLE
react-native run android - fail

### ISSUE THREAD

**Issue by NenadoPL1Z** [volga-volga/react-native-yamap#122]
При попытке запуска на андроиде выдает ошибку, на ios все нормально. Ошибка возникает после установки пакета

**Comment by NenadoPL1Z** [comment]
<img width="1403" alt="Снимок экрана 2022-06-07 в 11 24 21" src="https://user-images.githubusercontent.com/81239058/172311074-1f9031ca-a0c4-452b-b4f3-0f4af5073813.png">

**Comment by ownikss** [comment]
напиши пожалуйста версии рн и карт

**Comment by ownikss** [comment]
Вообще это warning - с ним приложение собирается. Сама ошибка ниже должна быть

**Comment by ownikss** [comment]
В версии 4.0.15 предупреждение исправили
