### ISSUE TITLE
Отладка нестабильно работает  

### ISSUE THREAD

**Issue by svirid132** [volga-volga/react-native-yamap#126]
Использую версию React Native 0.68.

При использовании reload и Fast Refresh приложение вылетает в эмуляторе android. Чтобы восстановить работу приходится заново запускать приложение через **npx react-native run-android**.

Как это выглядит:
![Peek 2022-06-12 21-08](https://user-images.githubusercontent.com/69749126/173247370-30f1db9f-6c36-406b-88dd-a1a7b583916a.gif)

Компонент, использующую библиотеку брал из: https://github.com/ownikss/rn-yamaps-example

**Comment by zoomerland** [comment]
У меня так же вылетает после каждого обновления. Но остается в фоне, и если через кнопку квадрата развернуть обратно, то приложение разворачивается и связь с дебагером восстанавливается. Попробуйте развернуть при вылете из фона, быстрее выходит чем через  react-native run-android

**Comment by ownikss** [comment]
Исправлено в 4.0.18
Если повторится - переоткройте issue
