### ISSUE TITLE
Неправильно работает fitAllMarkers на андроид

### ISSUE THREAD

**Issue by ownikss** [volga-volga/react-native-yamap#128]
Работает только если внутри метода вместо getChildCount хардкодить число

**Comment by ownikss** [comment]
Здесь же стоит посмотреть проблему для ios
https://github.com/volga-volga/react-native-yamap/issues/55

**Comment by Kt00s** [comment]
В YamapView всегда инициализируется child PlatformGLSurfaceView, как понял, он помогает в отрисовке карты и ее объектов на экране. Этот child не конвертируется в ReactMapObject, из-за этого происходит ошибка. Хотфикс уже есть

**Comment by ownikss** [comment]
Исправлено в версии 4.0.16

https://github.com/volga-volga/react-native-yamap/pull/129
