### ISSUE TITLE
На телефонах Сяоми при открытии экрана с картой появляется ошибка 

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#13]
![image](https://user-images.githubusercontent.com/20275419/72522041-c2dbd900-386d-11ea-9c94-217f9b4f63ec.png)

**Comment by ownikss** [comment]
Добавил дополнительных проверок на null. Попробуйте поставить версию с коммита

    yarn add git://github.com/volga-volga/react-native-yamap.git#2c55ee41aea
