### ISSUE TITLE
arm64 M1 iOS

### ISSUE THREAD

**Issue by SokolovRU** [volga-volga/react-native-yamap#130]
Приветствую. Наблюдаются проблемы с запуском на iOS M1. 
Изначально сделал eject и упирался в проблему архитектуры arm64. Сейчас пытаюсь запустить чистый проект с этой картой и тоже ухожу в ошибку.

Вопрос в следующем, есть ли тут разработки которые писали приложение с этой библиотекой на M1, были проблемы? Если да, то как фиксились?

Это проблема глобальна ( у Гугл карт подобное ), но я в надежде что решение есть!

**Comment by ownikss** [comment]
@Kt00s подскажи пожалуйста сталкивался ли с проблемой на m1?

Насколько знаю, у нас в команде проблемы на m1 не было.

Какие версии библиотек используются в чистом проекте? react-native, карты и может еще какие-то особенности есть

**Comment by eugnazaroff** [comment]
mac air m1, приложение не собирал, но при разработке никаких проблем не было выявлено, на эмуляторах/реальных устройствах четко работает

**Comment by SokolovRU** [comment]
Создаю новый проект -> npx react-native init test4
Запускаю смотрю что работает -> npx react-native run-ios
проект собрался и запустился 
докидываю рапу -> yarn add react-native-yamap

при инициализации карты падаю в null
YaMap.init('109f7cbc-6ea7-47f3-934f-caf9f436b20b');

Я просто решил идти очень маленькими шашками, я могу сразу приложить ошибку на eject-том проекте

**Comment by eugnazaroff** [comment]
в каком месте приложения происходит инициализация?

**Comment by SokolovRU** [comment]
сейчас в app файле. В приложении где был сделан Expo eject в файле где у меня экран карты ( там на андройде всё работает )

**Comment by SokolovRU** [comment]
так и сделано. может надо после установки сделать pod Install?

**Comment by SokolovRU** [comment]
<img width="1440" alt="Снимок экрана 2022-06-24 в 13 44 48" src="https://user-images.githubusercontent.com/105442172/175519434-23bc7ed9-bd7e-40a8-9c4a-ae813caa62d8.png">

**Comment by eugnazaroff** [comment]
pod-ы конечно надо установить

**Comment by SokolovRU** [comment]
Как и ожидалось всё пошло по одному месту. Я даже не знаю как сказать что я там вижу

**Comment by SokolovRU** [comment]
Я сейчас удалю Xcode и скачаю заново. Тут скорее всего ошибка из-за того что я уже там натыкал

**Comment by SokolovRU** [comment]
❌  ld: in /Users/denissokolov/workRN/transportmanagerby-3in1_tm_naitive-c90e1345d87f-main/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '/Users/denissokolov/workRN/transportmanagerby-3in1_tm_naitive-c90e1345d87f-main/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64 - это проблема на проекте с expo eject

**Comment by SokolovRU** [comment]
сейчас стало ломаться после Podspec install


2022-06-24 14:40:28.754 xcodebuild[10172:71112] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-24 14:40:28.754 xcodebuild[10172:71112] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
        Ld /Users/denissokolov/Library/Developer/Xcode/DerivedData/test4-ggdplykcvgeginahkdrysypvfkhb/Build/Products/Debug-iphonesimulator/test4.app/test4 normal (in target 'test4' from project 'test4')
(1 failure)

**Comment by eugnazaroff** [comment]
честно говоря, очень трудно понять какие шаги Вы делаете, зачем-то используете expo (про его поддержку в либе ничего не говорится). Я могу со 100% гарантией заявить, что следующий порядок работает:

- npx react-native init test
- yarn add react-native-yamaps
- npx pod-install

App.js - import .... YaMap.init(API_KEY)

-yarn ios

**Comment by SokolovRU** [comment]
После того как переустановил мак и накопил всё по новой, получилось. Пока не закрываю, т.к. есть вероятность что в другом проекте будет всё очень плохо.

По поводу експо - я сделал еджект, что является допустимым для работы этой библиотеки ( ну по крайне мере был вопрос как работать с экспо и был дан ответ сделать еджект )

**Comment by ownikss** [comment]
Это закрою. Если будут проблемы после eject, то лучше еще issue создать, чтобы название соответствовало проблеме

**Comment by Melber17** [comment]
Падает такая же ошибка `Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file  YandexMapsMobile' for architecture arm64`
Делал также 

> честно говоря, очень трудно понять какие шаги Вы делаете, зачем-то используете expo (про его поддержку в либе ничего не говорится). Я могу со 100% гарантией заявить, что следующий порядок работает:
> 
> * npx react-native init test
> * yarn add react-native-yamaps
> * npx pod-install
> 
> App.js - import .... YaMap.init(API_KEY)
> 
> -yarn ios

**Comment by tegozen** [comment]
Не знаю как кто тестил чтобы говорить что все работает, но 13.4.1 под м1 (не розетта и в режиме розеты)
не собирает приложение с данной библиотекой ни на эмулятор ни на устройство

**Comment by Melber17** [comment]
@tegozen , открыл новый issue #139 по этой ошибке
