### ISSUE TITLE
Нанесение маршрутов на карту

### ISSUE THREAD

**Issue by xakermonkey** [volga-volga/react-native-yamap#138]
Приветствую. Собственно вопрос из названия. Есть ли такая возможность или может кто то как то реализует данный механизм? Из документации нашел только как получить маршруты. А вот как нанести хотя бы один - проблема..

**Comment by ownikss** [comment]
Нанести можно используя компонент [Polyline](https://github.com/volga-volga/react-native-yamap#polyline)

**Comment by xakermonkey** [comment]
Спасибо, разобрался
