### ISSUE TITLE
Поддержка приложений expo

### ISSUE THREAD

**Issue by dimaokk** [volga-volga/react-native-yamap#147]
Есть ли поддержка приложений expo не могу найти выдает ошибку

**Comment by SokolovRU** [comment]
Не разработчик этой библиотеки, но если посмотреть закрытые таски, то был вопрос про Expo - https://github.com/volga-volga/react-native-yamap/issues/20

Мб он немного устарел, но я пробовал запускать на экспо пару месяцев назад и падал в такую же ошибку)
Выход Expo eject

**Comment by ownikss** [comment]
Мы не можем добавить нативную зависимость в экспо приложение. Для этого нужно чтобы весь наш java/objective c код внесли в ядро expo
Единственный вариант - сделать eject
