### ISSUE TITLE
Краш на macbook m1 (v 4.1.1, ios 15.5)

### ISSUE THREAD

**Issue by Djhitman** [volga-volga/react-native-yamap#153]
При рендере карты на ios отображается сетка карты и через секунду приложение вылетает 

```
import {YaMap, Suggest, Marker, Geocoder} from 'react-native-yamap';

<View style={{height: 200}}>
    <YaMap ref={c => mapRef.current = c} style={{flex: 1}}  />
</View>
```

Проблема только на ios симуляторе и macbook m1 (тестировал на macbook с intel процессором - все нормально)

версия библиотеки 4.1.1

`    "react-native-yamap": "^4.1.1",`

**Comment by vladkoshechkin** [comment]
https://github.com/volga-volga/react-native-yamap/issues/139

Уже создан issue
