### ISSUE TITLE
Ошибка Unable to resolve module 'react-native/Libraries/Image/resolveAssetSource

### ISSUE THREAD

**Issue by DaniilBabakin** [volga-volga/react-native-yamap#154]
Здравствуйте! Подскажите пожалуйста, пишет ошибку Unable to resolve module 'react-native/Libraries/Image/resolveAssetSource.js'. Перепробовал все , что было в интернете( к несчастью, "гайдов" было мало ).Ошибку выдает на этапе подключения( то есть я делаю импорт Yamap from 'react-native', а после этого сразу же появляется ошибка )

**Comment by ownikss** [comment]
Подскажи какая версия карт и версия react native?

**Comment by ch3rn1k** [comment]
@DaniilBabakin актуально еще? Пробовали реинстал `node modules`, `pods`?

**Comment by DaniilBabakin** [comment]
> @DaniilBabakin актуально еще? Пробовали реинстал `node modules`, `pods`?

Уже нет, спасибо. Помогло поставить другую версию карт

**Comment by ch3rn1k** [comment]
@ownikss можно закрывать, неактуально
