### ISSUE TITLE
Не работает initialRegion.

### ISSUE THREAD

**Issue by maxs1m** [volga-volga/react-native-yamap#160]
Доброго времени суток. Подскажите, почему могут не работать InitialRegion, делаю по инструкции, передаю в компонент YaMap  initialRegion={{
          lat: 50,
          lon: 100,
          zoom: 5,
          azimuth: 80,
          tilt: 100
        }}
(например). Но при открытии карты заново показыается общий вид. Как не менять значения, всегда общший вид.
До 4.1.2 обновился

**Comment by ch3rn1k** [comment]
Привет, исправил в #161, надо подождать мейнтейнера когда апрувнет

А так да, все верно ты инитишь `InitialRegion`

**Comment by ch3rn1k** [comment]
Протестировал версию `2.1.3` - проблемы нет, проверяйте

**Comment by maxs1m** [comment]
Заработало
