### ISSUE TITLE
Use of undeclared identifier 'YMKMapKit'

### ISSUE THREAD

**Issue by KAMRONBEK** [volga-volga/react-native-yamap#168]
как в документации добавил это: ```#import <YandexMapsMobile/YMKMapKitFactory.h>``` в ```AppDelegate.mm```
и потом Вызывал: ```[YMKMapKit setApiKey:@"API_KEY"];```,
но дает ошибку: ```Use of undeclared identifier 'YMKMapKit'```

**Comment by ch3rn1k** [comment]
Где именно указали импорт, в начале, в конце? Например у меня все работает примерно с таким кодом:

```C
#import "AppDelegate.h"

#import <YandexMapsMobile/YMKMapKitFactory.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAppSetupUtils.h>
```

```C
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  [YMKMapKit setLocale: @"ru_RU"];
  [YMKMapKit setApiKey: @"12345"];

  return YES;
}
```

P.S. Ключ лучше удалите из своего примера

**Comment by KAMRONBEK** [comment]
@ch3rn1k  поставил в начале, получилось, спасибо
