### ISSUE TITLE
getCameraPosition

### ISSUE THREAD

**Issue by pavelnaumov** [volga-volga/react-native-yamap#169]
Привет! Спасибо за классную либу, круто постарались 💪

Нашел один момент с методом `getCameraPosition`. В документации и в тестовом приложении с примером указано, что этот метод возвращает `CameraPosition`, т.е. можно обратиться к результату как `position.zoom`.
На деле, к этому полю можно обратиться только через `position.nativeEvent.zoom`; `position.zoom` будет `undefined`.
TypeScript так же ругается, что `Property 'nativeEvent' does not exist on type 'CameraPosition'.`

Прошу поправить документацию и тестовое приложение 🙏🏻

Заранее спасибо

**Comment by ownikss** [comment]
Исправили в версии 4.1.6

**Comment by pavelnaumov** [comment]
Спасибо за помощь! ✊🏻
