### ISSUE TITLE
Circle rendered under map labels

### ISSUE THREAD

**Issue by Reeywhaar** [volga-volga/react-native-yamap#171]
Hi!

I'm struggling to understand why Circle is rendered below map labels. Is it expected?. Setting zIndex doesn't help.

Thank you!

<img width="330" alt="image" src="https://user-images.githubusercontent.com/884649/186869194-b3e49875-943e-4487-adef-3b0b7a627c49.png">

**Comment by ch3rn1k** [comment]
Hello! Yeah, that is expected. POI shows on top level layer, same as Logo and Copyright.

If this confusing - you can hide all POI via `mapStyle` prop:
```jsx
<YaMap
  mapStyle={JSON.stringify([
    {
      types: ['point'],
      stylers: {
        visibility: 'off'
      }
    }
  ]}
/>
```

**Comment by Reeywhaar** [comment]
Thank you, now I understand!

Also, I've found out that I can switch to "raster" map type as a workaround :-)
