### ISSUE TITLE
Проблема со сборкой 

### ISSUE THREAD

**Issue by sawakawtira123** [volga-volga/react-native-yamap#172]
**Версия:**  xcode-13.0

m.apple.dt.IDEWatchSupportCore
 BUILD FAILED 

The following build commands failed:
        CompileC /Users/kateechkin/Library/Developer/Xcode/DerivedData/testMap-fwlyxvrimmdyklafgmjczavfawuw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNYamap.build/Objects-normal/x86_64/RNCYMView.o /Users/kateechkin/Desktop/testMap/node_modules/react-native-yamap/ios/View/RNCYMView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNYamap' from project 'Pods')
(1 failure)
![311f0474-9505-4915-a41f-eb57fe5205ee](https://user-images.githubusercontent.com/48391762/187650031-cfbb473b-3408-4099-bb95-58c7b6885d18.png)

**Зависимости:** 
![image](https://user-images.githubusercontent.com/48391762/187650283-25bfb5f0-d312-48db-a8ea-9bc25fbf7a53.png)

**Comment by ownikss** [comment]
В курсе проблемы. Временно стоит использовать предыдущую версию 4.1.6
В ближайшее время постараемся исправить проблему

**Comment by ch3rn1k** [comment]
> В курсе проблемы. Временно стоит использовать предыдущую версию 4.1.6 В ближайшее время постараемся исправить проблему

Привет, посмотрел доки яндекса и не нашел ничего про класс `YMKMasstransitOptions`, кхм

**Comment by ch3rn1k** [comment]
> В курсе проблемы. Временно стоит использовать предыдущую версию 4.1.6 В ближайшее время постараемся исправить проблему

Привет, разве класс этот не аутдейтет и его нет в версии >4.0?

В версии 3.0 нашел его https://yandex.com/dev/maps/archive/doc/mapkit/3.0/concepts/ios/mapkit/ref/YMKMasstransitOptions.html

**Comment by ch3rn1k** [comment]
Если заменить просто `YMKMasstransitOptions` на `YMKTransitOptions` - фокус удастся? :)

**Comment by ownikss** [comment]
Его нужно просто удалить. Проблема возникла при решении конфликта в ветке кластеризации. Конкретно эту проблему решили, но падает из за suggestions. Когда стабилизируем версию - опубликуем фикс

**Comment by ch3rn1k** [comment]
Понял, тогда не лезу

**Comment by sawakawtira123** [comment]
всем спасибо, помогло только понижение версии, сколько не копались пофиксить послднию версию не вышло

**Comment by ownikss** [comment]
Исправлено в версии 4.1.8
