### ISSUE TITLE
Exception thrown while executing UI block: -[RNYMView setInitialRegion:]: unrecognized selector sent to instance 0x7f7e23b55720

### ISSUE THREAD

**Issue by Splicer97** [volga-volga/react-native-yamap#175]
Выдает ошибку на симуляторе IOS если присутствует пропс initialRegion. Без него отображается просто пустая сетка. В AppDelegate.m ключи прокинул по инструкции.
    "react": "18.0.0",
    "react-native": "0.69.3",
    "react-native-yamap": "^4.1.6",

**Comment by Splicer97** [comment]
> А какая именно версия установлена? 4.1.6 или выше?

4.1.6 стоит. Поставил 4.1.7 и проект не билдился, 4.1.8 пока что не отображается в npmjs, там такой проблемы быть не должно?

**Comment by ch3rn1k** [comment]
> А какая именно версия установлена? 4.1.6 или выше?

Судя по коммитам вы случайно удалили `setInitialRegion` в #142 
Вернул в #176

**Comment by Splicer97** [comment]
> > А какая именно версия установлена? 4.1.6 или выше?
> 
> Судя по коммитам вы случайно удалили `setInitialRegion` в #142 Вернул в #176

На какую версию можно откатиться, чтобы карты работали под ios?

**Comment by ch3rn1k** [comment]
> > > А какая именно версия установлена? 4.1.6 или выше?
> > 
> > 
> > Судя по коммитам вы случайно удалили `setInitialRegion` в #142 Вернул в #176
> 
> На какую версию можно откатиться, чтобы карты работали под ios?

Я бы не торопился и подождал пару часов @ownikss, но если очень надо - 4.1.5 по идее должна работать

**Comment by Splicer97** [comment]
Отлично! 4.1.9 исправило ошибку с initialRegion. Спасибо )

> > > > А какая именно версия установлена? 4.1.6 или выше?
> > > 
> > > 
> > > Судя по коммитам вы случайно удалили `setInitialRegion` в #142 Вернул в #176
> > 
> > 
> > На какую версию можно откатиться, чтобы карты работали под ios?
> 
> Я бы не торопился и подождал пару часов @ownikss, но если очень надо - 4.1.5 по идее должна работать
