### ISSUE TITLE
Yamap.init

### ISSUE THREAD

**Issue by azokarta** [volga-volga/react-native-yamap#18]
![image](https://user-images.githubusercontent.com/32189402/81384032-e97e9200-9132-11ea-809c-23999600edc8.png)

помогите, в чем проблема?

**Comment by ownikss** [comment]
[Ответил в соседнем issue](https://github.com/volga-volga/react-native-yamap/issues/19#issuecomment-634223432) с подобной проблемой

Еще могу предположить что используете `expo cli`. В таком случае - библиотека работает только с react-native cli. Чтобы запустить в проекте с экспо нужно делать eject. Более подробно в [этом issue](https://github.com/volga-volga/react-native-yamap/issues/20#issuecomment-632347670)
