### ISSUE TITLE
Is this design and functionalities realisable with the library

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#181]
![IMG_20220912_124810](https://user-images.githubusercontent.com/36996198/189624413-6f3ea91e-e8d2-4b9a-b781-41e0da480108.jpg)

My question is , is that design (zoom buttons , and other buttons) with the possibility of seeing buses Moving in the card (data from our backend ) with this look or design with this library ? And which difficulties or issues should i take in considération when implementing such module ?

**Comment by ownikss** [comment]
1. You can use YamapView methods to zoom map. `setZoom `
2. You can set map center with any coordinates. For example you can get current user location. `setCenter `
3. You can zoom map to fit all given points. Use this method to fit polyline route. `fitMarkers`
4. I don't understand bus icon. Probably it's mean hide transit layer. To hide map layer you can use prop `mapStyle`
https://github.com/volga-volga/react-native-yamap/issues/185

**Comment by E-Viskhan** [comment]
> > 1. You can use YamapView methods to zoom map. `setZoom `
> > 2. You can set map center with any coordinates. For example you can get current user location. `setCenter `
> > 3. You can zoom map to fit all given points. Use this method to fit polyline route. `fitMarkers`
> > 4. I don't understand bus icon. Probably it's mean hide transit layer. To hide map layer you can use prop `mapStyle`
> >    [Скрыть оригинальные остановки #185](https://github.com/volga-volga/react-native-yamap/issues/185)
> 
> Should i get a ref of a the YaMap to access methods ? and what's the ref type in typescript ?

This answer is for future users:

Yes, you should get a ref of a the YaMap to access methods and typescript type for useRef is YaMap.

```
import YaMap from 'react-native-yamap';

const mapRef = useRef<YaMap>(null);

<YaMap ref={mapRef}>
...
</YaMap>

```
