### ISSUE TITLE
Есть ли возможность получить такой результат с помощью библиотеки 

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#182]
![IMG_20220912_124810](https://user-images.githubusercontent.com/36996198/189625304-d857e789-fb01-4b09-a042-1d444941d96a.jpg)

Вопрос такой , можно ли сделать такой дизайн ( кнопки зума , кнопка показать автобусы и тд ) 
В общем можно кастамизировать карту таким образом ? 
Можно ли добавить доведение автобусов как на приложении Яндекс карты ( данные из нашего Бека )? 
Насколько это реализируемый

**Comment by ch3rn1k** [comment]
Что мешает создать свой компонент кнопки поверх карты и сделать ему функции?

**Comment by anisamirouche** [comment]
> Что мешает создать свой компонент кнопки поверх карты и сделать ему функции?

Да как можно поставить кнопки поверх карты ?

**Comment by ch3rn1k** [comment]
> > Что мешает создать свой компонент кнопки поверх карты и сделать ему функции?
> 
> 
> 
> Да как можно поставить кнопки поверх карты ?

Средствами стилей, как обычно:

'position: absolute', 'zIndex: 9999'
