### ISSUE TITLE
Маркер, показывающий синюю точку по умолчанию при первом рендеринге

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#183]
```js
<YaMap>
        <Marker
          point={{ lat: 50, lon: 50 }}
          scale={3}
          source={require('./src/assets/transport.png')}
        />
</YaMap>
```
Маркер, показывающий синюю точку по умолчанию при первом рендеринге, если я изменяю scale, отображается моя иконка, но если я перезагружаю приложение, это снова синяя точка отображантся вместе моей картинки
![photo_5260227296055377726_y](https://user-images.githubusercontent.com/36996198/189685152-44fbe2dc-5d3e-417c-9526-7a442e6be726.jpg)

**Comment by anisamirouche** [comment]
```js
<Marker
        point={{ lat: 50, lon: 50 }}
          scale={3}
      >
        <Image
          source={require('./src/assets/transport.png')}
        />
      </Marker>
```
this solved the problem

**Comment by OctoMammoth** [comment]
> ```js
> <Marker
>     point={{ lat: 50, lon: 50 }}
>     scale={3}>
>     <Image
>          source={require('./src/assets/transport.png')}
>      />
> </Marker>
> ```
> 
> this solved the problem

Now working
