### ISSUE TITLE
Скрыть оригинальные остановки

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#185]
Есть ли возможность скрыть оригиналные остановки ?

**Comment by ownikss** [comment]
Это можно сделать используя пропс mapStyle. Туда передается описание стиля карты
Примерный вариант будет выглядеть так.

Подробнее можно посмотреть в нативной документации https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/style.html

```jsx
<YaMap
  mapStyle={JSON.stringify([
    {
      types: ['point'],
      tags: { all: ['transit'] },
      stylers: {
        visibility: 'off'
      }
    }
  ]}
/>
```
