### ISSUE TITLE
Remove userLocationAccuracyStroke

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#186]
Is there anyway to remove userLocationAccuracyStroke 
i tried to give him transparent as value and userLocationAccuracyStrokeWidth to 0 but the circle is still showing

**Comment by ownikss** [comment]
Give a few information please:
- react-native-yamap version
- react-native version
- platform with problem: ios/android/both

**Comment by anisamirouche** [comment]
- react-native-yamap version : 4.1.10
- react-native version: 0.69.5 and 0.63.4 i'm actually 
     implementing it in both these versions
- platform with problem: both

for furthure information please look at the picture, there is a blue circle around user position icon (userLocationAccuracyStroke)

**Comment by ch3rn1k** [comment]
Well, I haven't tried that hacky way, but try this:
```jsx
<YaMap
  userLocationAccuracyStrokeColor="rgba(0, 0, 0, 0)"
/>
```

**Comment by anisamirouche** [comment]
> ```js
>   userLocationAccuracyStrokeColor="rgba(0, 0, 0, 0)"
> ```

this is not working

**Comment by ch3rn1k** [comment]
> > ```js
> >   userLocationAccuracyStrokeColor="rgba(0, 0, 0, 0)"
> > ```
> 
> this is not working

Will check later, mb will do something

**Comment by Floreniano** [comment]
> > ```js
> >   userLocationAccuracyStrokeColor="rgba(0, 0, 0, 0)"
> > ```
> 
> Это не работает

you can try this rgba(255, 255, 255, 0.1)

**Comment by ch3rn1k** [comment]
This one work for me fine:

```jsx
userLocationAccuracyFillColor="rgba(0, 0, 0, 0)"
userLocationAccuracyStrokeColor="rgba(0, 0, 0, 0)"
userLocationAccuracyStrokeWidth={10}
```

**Comment by anisamirouche** [comment]
> > > ```js
> > >   userLocationAccuracyStrokeColor="rgba(0, 0, 0, 0)"
> > > ```
> > 
> > 
> > Это не работает
> 
> you can try this userLocationAccuracyFillColor="rgba(255, 255, 255, 0.1)"

It's working very good , thanks

**Comment by anisamirouche** [comment]
Solution : 
userLocationAccuracyFillColor="rgba(255, 255, 255, 0.1)
