### ISSUE TITLE
YaMapView

### ISSUE THREAD

**Issue by azokarta** [volga-volga/react-native-yamap#19]
![image](https://user-images.githubusercontent.com/32189402/81384979-60685a80-9134-11ea-806c-17f4c902f554.png)

что делать?

**Comment by ownikss** [comment]
Какую версию react native используете?

В целом проблема в том что библиотека не прилинкована. Если используете react native **60+** то там работает автолинкинг. Для того чтобы компонент стал доступен достаточно сделать `pod install` в папке ios и пересобрать ios проект

Если react-native версии **ниже 60**, то необходимо выполнить `react-native link react-native-yamap`. Далее - выполнить `pod install` и пересобрать проект
