### ISSUE TITLE
Активный маркер

### ISSUE THREAD

**Issue by xGum** [volga-volga/react-native-yamap#2]
Необходимо сделать чтобы активный маркер был поверх других иначе активный маркер перекрывается
![image](https://user-images.githubusercontent.com/3848735/70790573-6b49d980-1da6-11ea-9f04-3083da43cd19.png)

**Comment by ownikss** [comment]
В следующей версии будет обновлена модель маркера. Будет удален параметр selected. Для кастомизации изображения маркера можно будет передать параметр source, как в компоненте Image.
Для отображения маркера поверх других можно будет использовать параметр маркера zIndex
Новая модель маркера:
```
{
  lat: number,
  lon: number,
  id?: string,
  source?: ImageSource,
  zIndex?: number,
}
```
Эти изменения будут в версии **1.1.0**
