### ISSUE TITLE
TypeError: null is not an object (evaluating 'yamap.init')

### ISSUE THREAD

**Issue by nmihalyov** [volga-volga/react-native-yamap#20]
Использую react-native-yamap в expo cli.
Устанавливал через `expo install react-native-yamap`

Код компонента:
![Screenshot at May 21 18-58-04](https://user-images.githubusercontent.com/15937747/82578410-06847d80-9b95-11ea-997a-751643b1c285.png)

Ошибка:
![IMAGE 2020-05-21 18:57:03](https://user-images.githubusercontent.com/15937747/82578274-dd63ed00-9b94-11ea-9beb-cac5b92e1fed.jpg)

**Comment by ownikss** [comment]
Библиотека работает только в react native cli. С expo использовать не получится - это обертка над нативным sdk, которое не включено в expo. Чтобы использовать эту библиотеку придется сделать eject.
Любая обертка над нативным сдк яндекс карт будет требовать eject. Возможно в Вашем случае подойдет решение с webview и веб версией карт

**Comment by Aziaev** [comment]
@ownikss А можно подробнее рассказать как с eject использовать вашу библиотеку?
