### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RNYamap":   In Podfile:

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#216]
[!] CocoaPods could not find compatible versions for pod "RNYamap":
  In Podfile:
    RNYamap (from `../node_modules/react-native-yamap`)

Specs satisfying the `RNYamap (from `../node_modules/react-native-yamap`)` dependency were found, but they required a higher minimum deployment target.

React native: 0.63.4

**Comment by ownikss** [comment]
Минимальная версия ios для использования библиотеки: 12.0

Чтобы решить проблему нужно поднять target версию в xcode и в Podfile
