### ISSUE TITLE
Execution failed for task 'react-native-yamap:verifyReleaseResources' при собрании билда релиза

### ISSUE THREAD

**Issue by anisamirouche** [volga-volga/react-native-yamap#218]
у нас такая ошибка есть при собрании релизового билда на андроиде
если билд на debug то все нормално
```java 
❯ ./gradlew assembleRelease
```
react-native: 0.70.5
react: 18.1.0
react-native-yamap: 4.1.14

![photo_2022-12-13_15-28-18](https://user-images.githubusercontent.com/36996198/207319737-c160b0de-2a8f-4379-8a3d-c689e8a13314.jpg)

**Comment by AlexKiZer** [comment]
Такая же проблема

**Comment by joratapok** [comment]
+1

**Comment by RouberR** [comment]
В моем случае помогло поднятие compileSdkVersion до 31 в самой библиотеке, node_modules->react-native-yamap->android->build.gradle

**Comment by kon-alt** [comment]
> В моем случае помогло поднятие compileSdkVersion до 31 в самой библиотеке, node_modules->react-native-yamap->android->build.gradle

Работает!

**Comment by ownikss** [comment]
Обновили compileSdkVersion в библиотеке. Версия в npm: 4.1.18
