### ISSUE TITLE
Как скроллить к позиции пользователя?

### ISSUE THREAD

**Issue by Spyspyspy** [volga-volga/react-native-yamap#22]
Добрый день, столкнулся со следующей проблемой - не могу скроллить к позиции пользователя при загрузке карты. Как это можно сделать?

**Comment by ownikss** [comment]
Вероятно это то что вам нужно - метод `setCenter`
https://github.com/volga-volga/react-native-yamap#методы

**Comment by Spyspyspy** [comment]
Смотрите, я делаю так : 

`ref={ref => (this.mapView = ref)}`

Затем вызываю этот метод: 

`this.mapView.setCenter(region);`


Но mapView почему-то undefined, не подскажете в чем проблема?

**Comment by ownikss** [comment]
Вероятнее всего этот `this.mapView.setCenter(region);` код вызывается до маунта компонента. Чтобы все ref были инициализированы нужно вызывать код не раньше `componentDidMount` в вашем компоненте
