### ISSUE TITLE
Не прогружается карта на Android

### ISSUE THREAD

**Issue by fonderkin** [volga-volga/react-native-yamap#231]
![2023-02-08_08-17-22](https://user-images.githubusercontent.com/16304172/217420584-f3a41d86-0952-401e-80d8-bd3b78e08340.png)

Функция onMapLoaded не срабатывает

```
return (
    <View flex>
      <YaMap
        onMapLoaded={() => console.log('loaded')}
        userLocationIcon={{
          uri: 'https://www.clipartmax.com/png/middle/180-1801760_pin-png.png',
        }}
        initialRegion={{
          lat: 50,
          lon: 50,
          zoom: 10,
        }}
        style={{flex: 1}}>
        <Marker point={{lat: 50, lon: 50}} />
      </YaMap>
    </View>
  );
```

```
 "react": "18.2.0",
 "react-native": "0.71.1",
 "react-native-yamap": "^4.1.17",
```

**Comment by fonderkin** [comment]
Сразу пометка разработчикам, внести в документацию информацию о том, что нужно получать ключ для MapKit, а не Яндекс Javascript Map.

Но это тоже не спасло ситуацию.

**Comment by fonderkin** [comment]
Несколько часов танцев с бубнами и магическим образом заработало)

**Comment by E-Viskhan** [comment]
> Несколько часов танцев с бубнами и магическим образом заработало)

В документации указано, что api_key начинает работать примерно через 15 минут, так что возможно дело в этом
