### ISSUE TITLE
Есть ли возможность брать координаты выше центра? 

### ISSUE THREAD

**Issue by RouberR** [volga-volga/react-native-yamap#232]
Есть ли возможность брать координаты выше центра через функцию onCameraPositionChangeEnd например или как-то иначе. Для реализации фейк маркера, к примеру как в яндекс такси. ( На данный момент единственный костыль который помогает
 height: '142%',
 top: '-42%',
 но это вызывает неприятный результат на андроиде при навигации на предыдущий экран)
![H-k0QhT5V84](https://user-images.githubusercontent.com/89776006/218227125-3ea658ad-7798-4758-bf52-d949075e123e.jpeg)

**Comment by ownikss** [comment]
Я не понял что подразумевается под фейк маркером, но кажется задачу можно решить используя anchor.
Anchor устанавливает центр маркера относительно координат точки. По умолчанию x: 0.5, y: 0.5 - центр маркера совпадает с координатой точки.
Если нужно чтобы нижняя точка иконки указывала на координату маркера, то можно установить x: 0.5, y: 1 (возможно 0 - не помню в какую сторону срабатывает смещение)
