### ISSUE TITLE
RN 0.71.5 - ошибки при использовании пакета

### ISSUE THREAD

**Issue by dukvanduken** [volga-volga/react-native-yamap#240]
Столкнулся с невозможностью использования компонента в RN 0.71.5.

**Ошибка 1**

Код:
```
import YaMap from 'react-native-yamap'

YaMap.init('70f8e719-df7a-4c22-951c-4804a1c440cb')
```

Результат:
`TypeError: Cannot read property 'init' of null, js engine: hermes`
 
**Ошибка 2**

Код:
```
export default function App() {
  return (
    <View style={styles.container}>
      <YaMap
        userLocationIcon={{ uri: 'https://www.clipartmax.com/png/middle/180-1801760_pin-png.png' }}
        initialRegion={{
          lat: 50,
          lon: 50,
          zoom: 10,
          azimuth: 80,
          tilt: 100
        }}
        style={{ flex: 1 }}
      />
    </View>
  )
}
```

Результат:
```
This error is located at:
    in YamapView (created by YaMap)
    in YaMap (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  Invariant Violation: requireNativeComponent: "YamapView" was not found in the UIManager.
```

**Comment by zcdev02** [comment]
import {YaMap} from "react-native-yamap"; 

Попробуй так

**Comment by ownikss** [comment]
Приложение пересобиралось после установки зависимости? Выглядит так, что React Native просто не прилинковал зависимость, поэтому не может использовать нативный модуль

**Comment by dukvanduken** [comment]
> import {YaMap} from "react-native-yamap";
> 
> Попробуй так

@zcdev02 нет, то  же самое. Забава в том, что console.log(YaMap.init) говорит, то это функция.

**Comment by dukvanduken** [comment]
> 

@ownikss насколько я понял, линковать RN > 0.6 должен автоматом. А как прилинковать вручную в моём случае?

**Comment by dukvanduken** [comment]
@ownikss И, тем не менее, не работает. Проблемы, как я описал в первом сообщении.

**Comment by Capsonchik** [comment]
Работает ли данное решение с EXPO, сейчас у меня помимо ошибки init, просто не отображается ничего. Мучаюсь 4й день ....

**Comment by ViktoriaMityaeva** [comment]
> Работает ли данное решение с EXPO, сейчас у меня помимо ошибки init, просто не отображается ничего. Мучаюсь 4й день ....

Добрый день. Получилось решить ошибку, оставив expo?
