### ISSUE TITLE
Якоря для Marker

### ISSUE THREAD

**Issue by Ilya1995** [volga-volga/react-native-yamap#28]
Привет! Можешь добавить якорь для компонента Marker?

**Comment by ownikss** [comment]
Добавлю в ближайшей версии (1.0.18). Постараюсь найти время в ближайшие две недели

**Comment by ownikss** [comment]
Реализовано в версии 1.0.18. Пропс `anchor: {x: number, y: number}` для компонента Marker. Документация обновлена
