### ISSUE TITLE
Метод setZoom()

### ISSUE THREAD

**Issue by Ilya1995** [volga-volga/react-native-yamap#29]
Привет! Очень не хватает метода setZoom(). Например, пользователь пролистал карту до определенной точки и хочет с помощью кнопки приблизить || отдалить ее

**Comment by ownikss** [comment]
Планирую следующие доработки по этой задаче:
- просто метод `setZoom` который будет менять zoom на карте
- метод `getCameraPosition`, который вернет текущее положение камеры (в том числе зум)
- колбек `onCameraPositionChange`

Добавлять функционал буду в описанном порядке. setZoom смогу реализовать в ближайшей версии (1.0.18)

**Comment by ownikss** [comment]
Все доработки из комментария выше выполнены в версии 1.0.18. Документация обновлена
