### ISSUE TITLE
Android: Problem with marker display: null cannot be cast to non-null type

### ISSUE THREAD

**Issue by haykaslanyan13** [volga-volga/react-native-yamap#291]
The problem occurs after the update version from 4.1.18 to 4.6.0.
The problem occurs when passing the source prop to the Marker component
![Screenshot_1721494900](https://github.com/user-attachments/assets/27c0322f-c27d-4616-96c2-dc4f70e7bf5e)
<img width="651" alt="Screenshot 2024-07-20 at 21 04 50" src="https://github.com/user-attachments/assets/06a12aa4-6cea-4d21-bfd3-efcf9df80db2">

**Comment by avetisyan66** [comment]
Same problem, any solution? on iOS works perfect, but on android have bug
<img width="405" alt="Screenshot 2024-08-03 at 19 24 59" src="https://github.com/user-attachments/assets/6a630cb3-d905-41e0-aa2f-5be3719dc926">

**Comment by haykaslanyan13** [comment]
Fixed in version 4.6.1
