### ISSUE TITLE
Android: getChildAt(...) must not be null

### ISSUE THREAD

**Issue by youngblader** [volga-volga/react-native-yamap#299]
<img width="322" alt="Снимок экрана 2024-09-23 в 13 34 29" src="https://github.com/user-attachments/assets/6aec9285-379c-4dcc-9d41-127e58e6d488">

 "react-native-yamap": "^4.6.1",

Крашит. Скорее всего где-то отсутствует проверка на null. ClustersYamapView.

**Comment by miisemaks** [comment]
у меня выходит такая же ошибка

**Comment by ownikss** [comment]
Fixed in version 4.8.2
