### ISSUE TITLE
Не работает центр карты и зум

### ISSUE THREAD

**Issue by xGum** [volga-volga/react-native-yamap#3]
Какие бы параметры не передавали в карту - её центр и зум не меняется

**Comment by ownikss** [comment]
есть некоторые странности в поведении center - он отрабатывает при рендере, но при этом не фиксирует позицию центра. Еще при рендере маркеров вызывается метод `fitAllMarkers` который подбирает центр и зума так, чтобы все маркеры убрались на карту
В следующей версии постараюсь убрать center из пропсов, чтобы не вводить в заблуждение, что параметр фиксирует положение центра. Вместо этого предоставлю методы, которые можно будет вызвать по ref
