### ISSUE TITLE
Получение координат в точке нажатия

### ISSUE THREAD

**Issue by ApollonSeven** [volga-volga/react-native-yamap#33]
Добавьте пожалуйста возможность передачи координат в точке нажатия, для генерации маркеров в этих точках! Очень не хватает.

**Comment by ownikss** [comment]
Добавлено в версии  [1.0.19](https://github.com/volga-volga/react-native-yamap/releases/tag/v1.0.19)
События onMapPress и onMapLongPress. События возвращают координаты точки
