### ISSUE TITLE
[Пожелание] Добавить события onMapPressIn и onMapPressOut

### ISSUE THREAD

**Issue by ApollonSeven** [volga-volga/react-native-yamap#35]
Добавить события onMapPressIn и onMapPressOut
При использовании onMapPressLong, карта реагирует на нажатие в одной точке с задержкой. То есть если пользователь нажал на карту, скроллит и не отпускает, то событие не срабатывает.

**Comment by ownikss** [comment]
вообще сейчас все апи по нажатию на карту проброшено. За это отвечает интерфейс InputListener. У него есть только события onMapTap и onMapLongTap. Посмотрю варианты по этой проблеме

**Comment by ApollonSeven** [comment]
Нашел аналоги событий:
```javascript
onTouchStart?: (event: GestureResponderEvent) => void;
onTouchEnd?: (event: GestureResponderEvent) => void;
```
