### ISSUE TITLE
Не работает на ios

### ISSUE THREAD

**Issue by arthurg91** [volga-volga/react-native-yamap#37]
Под последние версии ios(симулятор, реальный девайс) не грузится карта вообще, белый холст(хотя другая интерактивность присутствует например выставление центра и зум), на android через раз грузиться.

**Comment by ownikss** [comment]
Подготовил [example](https://github.com/ownikss/rn-yamaps-example) для библиотеки. Воспроизводится ли проблема в этом репозитории? в readme к примеру написано как его запустить

**Comment by arthurg91** [comment]
На демке все оке)!

**Comment by vsavitskiy** [comment]
@arthurg91 привет! если проблема разрешилась напиши пожалуйста в чем она заключалась

**Comment by arthurg91** [comment]
Причины бага не удалось выяснить)

**Comment by sgarsa667** [comment]
Была похожая ситуация, установил пакет, указал ключ, но после билда, был белый холст. Помог `Clean` проекта. После этого было все норм.
