### ISSUE TITLE
Scroll Map

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#4]
Если YaMap помещен в ScrollView,  то управлять картой невозможно, у react-native-maps такого нет

**Comment by ownikss** [comment]
Такое же поведение и при использовании mapkit в нативном приложении. Я так понимаю яндекс пока не предлагают решения этой проблемы

https://github.com/yandex/mapkit-ios-demo/issues/15

И аналогичное issue в немного устаревшем репозитории:
https://github.com/yandexmobile/yandexmapkit-android/issues/296

От себя могу предложить может не самое корректное, но теоретически рабочее решение - поместить карту снаружи скрола на абсолюте и двигать ее на onScroll у ScrollView. А внутри ScrollView рендерить пустое View под карту. При использовании нативного драйвера анимации для обработки скрола я думаю лагать не должно. По сути поведение похожее на CollapsingToolbar
в таком например стиле https://medium.com/@habibridho/implementing-collapsing-toolbar-using-react-native-4a84e1718f11

**Comment by azesmway** [comment]
Придумал извращенное решение этой проблемы)))

`const [isCanCancelContentTouches, setCanCancelContentTouches] = React.useState(true);

<ScrollView
                canCancelContentTouches={isCanCancelContentTouches}
                scrollEnabled={isCanCancelContentTouches}
>
   <View style={[outerStyle]} onTouchStart={() => setCanCancelContentTouches(false)} onTouchEnd={() => setCanCancelContentTouches(true)}>
      <YaMap ref={mapRef}
             style={styles.radioContainer}
             {...restProps}   
      >
      </YaMap>
   </View>
</ScrollView>`
