### ISSUE TITLE
Как задать конкретную версию MapKit?

### ISSUE THREAD

**Issue by adimshev** [volga-volga/react-native-yamap#41]

**Comment by ownikss** [comment]
Версия для ios можно указать в своем  Podfile прописав версии явно. Примерно так: 
```
pod "YandexMapKit", '~> 3.5.0'
pod "YandexMapKitDirections", '~> 3.5.0'
pod "YandexMapKitTransport", '~> 3.5.0'
```
Версия для андроид задается в файле `/android/build.gradle`. Сейчас ее нельзя изменить снаружи. Можно сделать переменную, которая будет подтягиваться из корня проекта

Но скорее всего это не имеет смысла, потому что обратной совместимости у яндекса нет, поэтому переключить версию не получится - просто не соберется код для обертки. Для андроид сейчас используется 3.2.0. Повысить невозможно - [issue в репозитории sdk](https://github.com/yandex/mapkit-android-demo/issues/116)
Для ios используется 3.5.0. Возможно не сломается изменение версии до 3.4, но точно менялось апи при переходе в районе версии 3.3

Для чего конкретно нужно изменить версию skd?

**Comment by adimshev** [comment]
Когда делаешь релиз под iOS приходится отключать byte code, иначе апп не работает
