### ISSUE TITLE
Warning: Module YamapView requires main queue setup

### ISSUE THREAD

**Issue by diyorbek** [volga-volga/react-native-yamap#42]
Я настроил все по Readme. В андроиде все хорошо работает. Но в iOS я получаю эти "warning"и.
Что пошло не так?

<img width="320" alt="Screen Shot 2020-09-17 at 21 12 08" src="https://user-images.githubusercontent.com/29589560/93516675-aaefb400-f92a-11ea-8057-292062cada88.png">
<img width="321" alt="Screen Shot 2020-09-17 at 21 08 55" src="https://user-images.githubusercontent.com/29589560/93516686-af1bd180-f92a-11ea-846b-a8dbfa4896a8.png">

**Comment by v0lume** [comment]
same issue, rn 0.63.2

**Comment by alexdarh** [comment]
same issue

**Comment by ownikss** [comment]
Исправлено в версии 4.0.3

**Comment by akbako** [comment]
Вновь появился проблема
 - RN: 0.69.12 
- react-native-yamap: "4.6.1



<img width="547" alt="image" src="https://github.com/user-attachments/assets/8b9df812-4ee2-4a89-85cc-a960d0ce7691" />
