### ISSUE TITLE
Use of undeclared identifier 'YMKMapKit'

### ISSUE THREAD

**Issue by pedrogarciyalopez** [volga-volga/react-native-yamap#50]
Пытаюсь выполнить вот эту рекомендацию:

Рекомендуется инициализировать MapKit в функции didFinishLaunchingWithOptions в AppDelegate.m
```
#import <YandexMapKit/YMKMapKitFactory.h>
...

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    ...
    [YMKMapKit setApiKey: @"API_KEY"];
    return YES;
}
```
при этом не билдится релизная сборка с ошибкой: Use of undeclared identifier 'YMKMapKit', в дебаге все нормально.

В чем может быть причина?

**Comment by pedrogarciyalopez** [comment]
Проблема решается добавлением импорта `#import <YandexMapKit/YMKMapKitFactory.h>` в AppDelegate.h.
Думаю, это следует добавить в документацию.

**Comment by Umar-Juraev** [comment]
> Проблема решается добавлением импорта `#import <YandexMapKit/YMKMapKitFactory.h>` в AppDelegate.h. Думаю, это следует добавить в документацию.

Здравствуйте , после добавления : 'YandexMapKit/YMKMapKitFactory.h' file not found пишет.
Удаления Под файла и переустановка не помогла. 
Не знаете как решить ?

**Comment by svyatoslavratov** [comment]
@Umar-Juraev  #import <YandexMapsMobile/YMKMapKitFactory.h>
