### ISSUE TITLE
Приложение крашится из-за карт с ошибкой

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#51]
Падает на андроид

<details>
<summary>Скрины с отчетом об ошибке</summary>

![Screenshot_2021-02-19-16-13-46-509_com miui bugreport](https://user-images.githubusercontent.com/20275419/108511903-947ec780-72d1-11eb-8cf1-64855f2761bf.jpg)
![Screenshot_2021-02-19-16-13-51-543_com miui bugreport](https://user-images.githubusercontent.com/20275419/108511911-96488b00-72d1-11eb-95bd-baf64d6ef062.jpg)
![Screenshot_2021-02-19-16-19-05-806_com android settings](https://user-images.githubusercontent.com/20275419/108511913-9779b800-72d1-11eb-91f0-1ff040cad677.jpg)
![Screenshot_2021-02-19-16-19-14-076_com android settings](https://user-images.githubusercontent.com/20275419/108511917-98124e80-72d1-11eb-95ca-423089449f12.jpg)

</details>

**Comment by nmzgnv** [comment]
Та же самая проблема

**Comment by ownikss** [comment]
@nmzgnv 
Попробуйте версию `1.1.0-beta`
В ней обновлен sdk для андроид и ошибка кажется не воспроизводится

**Comment by nmzgnv** [comment]
Уже использую 1.1.0-beta, всё-равно вылетает😫

**Comment by Azshar** [comment]
Обновление до 4.0.0 помогло
