### ISSUE TITLE
[Пожелание]Кластеризация маркеров

### ISSUE THREAD

**Issue by MoronovArt** [volga-volga/react-native-yamap#54]
Не хватает функции кластеризации маркеров на карте, и колбэка onCameraPositionChangeEnd

**Comment by MoronovArt** [comment]
Привет, @ownikss 
Очень не хватает onCameraPositionChangeEnd был бы признателен если б добавили, когда планируется выпуск 21 версии?

**Comment by ownikss** [comment]
В 4.0.13 реализовали кластеризацию маркеров

**Comment by ownikss** [comment]
Вторую задачу вынес в отдельное issue

https://github.com/volga-volga/react-native-yamap/issues/124
