### ISSUE TITLE
Rebuild from Bitcode

### ISSUE THREAD

**Issue by norflin321** [volga-volga/react-native-yamap#56]
![Screenshot from 2021-04-24 08-12-02](https://user-images.githubusercontent.com/33498670/115948130-e4962800-a4d4-11eb-9e58-f4fc1dffbfb1.png)
When packing .ipa, if additional option "Rebuild from Bitecode" is checked then i get error: "ipatool failed with an exception: #<CmdSpec::NonZeroExitException". When unchecked everything is fine.

"react": "16.13.1",
"react-native": "0.63.2",
"react-native-yamap": "1.0.20"
Xcode version 11.2.1.

Is it problem with my settings or this library?

**Comment by norflin321** [comment]
#41

**Comment by ownikss** [comment]
Кажется в 4.1.5 проблема не актуальна
