### ISSUE TITLE
Подскажите, можно ли ли объединять маркеры при уменьшении зума карты ? 

### ISSUE THREAD

**Issue by StIch0** [volga-volga/react-native-yamap#57]

**Comment by labtorie** [comment]
Я думаю, можно брать значение зума методом getCameraPosition и самостоятельно сливать маркеры, дельта координат которых меньше порога

**Comment by StIch0** [comment]
@labtorie я пробовал манипулировать массивом точек самостоятельно, но тогда возникает ошибка на андройде `java.lang.RuntimeException: Native object's weak_ptr for `

**Comment by victorzimnikov** [comment]
> @labtorie я пробовал манипулировать массивом точек самостоятельно, но тогда возникает ошибка на андройде `java.lang.RuntimeException: Native object's weak_ptr for `

Привет! Удалось ли решить проблему? Столкнулся с такой же при динамической смене маркеров

**Comment by StIch0** [comment]
> > @labtorie я пробовал манипулировать массивом точек самостоятельно, но тогда возникает ошибка на андройде `java.lang.RuntimeException: Native object's weak_ptr for `
> 
> Привет! Удалось ли решить проблему? Столкнулся с такой же при динамической смене маркеров

Нет пришлось вырубить метод на android

**Comment by ownikss** [comment]
Кластеризация реализована в версиях начиная с 4.0.13
