### ISSUE TITLE
Проблемы с построением маршрута через пропс route и колбеком onRouteFound

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#6]
Маршрут не строится, в console.log SyntheticEvent, у всех свойств значение null

**Comment by ownikss** [comment]
Немного поправил логику в маршрутах, сейчас на простых примерах строится. Насчет `onRouteFound` - у event нужно логать именно event.nativeEvent. Если выводить просто event, то отобразится что везде лежит null, но это не так - особенности отладки в рн

**Comment by Azshar** [comment]
Событие handleOnRouteFound не работает при инициализации

**Comment by ownikss** [comment]
В [версии 1.0.11](https://github.com/volga-volga/react-native-yamap/releases/tag/v1.0.11) было полностью [переработано апи](https://github.com/volga-volga/react-native-yamap#%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%BE%D0%B2) для работы с маршрутами. Получение списка маршрутов теперь работает через ref метод, а сами маршруты приходят в колбеке, который передан вместе с запросом.
Параметр onRouteFound удален и больше не используется

Если возникнут проблемы в работе с новым апи, создайте новое issue
