### ISSUE TITLE
Событие onMapLongPress работает как onMapPress на IOS

### ISSUE THREAD

**Issue by nikitabudkovskiy** [volga-volga/react-native-yamap#61]
На последней версии 1.1.0-beta на IOS версии событие у карты YaMap onMapLongPress работает как onMapPress.

```
    "react": "17.0.1",
    "react-native": "^0.64.1",
```

**Comment by ch3rn1k** [comment]
Судя по коду - там все согласно документации Яндекса и должно работать как надо. Проблема до сих пор имеется?

**Comment by ownikss** [comment]
Актуальная версия библиотеки 4.1.6, проблема выглядит неактуальной. Если потребуется - переоткройте issue
