### ISSUE TITLE
Как изменить размер userLocationIcon?

### ISSUE THREAD

**Issue by nmzgnv** [volga-volga/react-native-yamap#64]
Размер userLocationIcon отличается в release и debug версиях, что отражено в Readme. 
**Но могу ли я задать размер этой иконки?**

**Comment by ownikss** [comment]
В нативном sdk mapkit можно указывать только scale для изображения, а не сами размеры. Для того чтобы размер был одинаковым в релизе и дебаге нужно добавлять в нативные ассеты

В нашей обертке не реализован этот параметр. Постараемся добавить в следующих релизах, но его наличие не решает проблему выше (хотя такой костыль решит проблему scale=1/PixelRatio.get())

**Comment by ch3rn1k** [comment]
@ownikss #196

**Comment by ownikss** [comment]
Добавлено в версии 4.1.14
