### ISSUE TITLE
Не отображается Marker

### ISSUE THREAD

**Issue by nmzgnv** [volga-volga/react-native-yamap#65]
![image](https://user-images.githubusercontent.com/46592780/128673888-f2e93458-a939-4826-9250-3764267d1b24.png)
На скриншоте показано, что не все иконки отображаются. 

Использую компонент Marker, children={<MarkerImage />} (Обычная картинка, добавил заливку для наглядности)

```
export const MarkerImage = () => {
  return (
    <Image
      style={{
        width: 25,
        height: 25,
        backgroundColor: 'blue',
      }}
      source={require('../../../assets/icons/marker.png')}
    />
  );
};
```

Как сделать корректный рендер? Есть ли другой способ задать иконку маркера?

_Дополнительно:_
```
markersToRender.map((point, key) => (
            <Marker
              key={key}
              point={{
                lon: point.Coordinates.Longitude,
                lat: point.Coordinates.Latitude,
              }}
              onPress={() => onMarkerPress(point)}>
              <MarkerImage />
            </Marker>
          ))
        )}
```

**Comment by ownikss** [comment]
Можно передать иконку маркера прямо в компонент Marker. [Фрагмент из доки](https://github.com/volga-volga/react-native-yamap#%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D1%8B%D0%B5-props)

**Comment by nmzgnv** [comment]
Передал иконку в компонент (source) -> не подгружалась (были синие точки)
Поменял картинку, стало работать. Спасибо👍
