### ISSUE TITLE
UserLocation Image 

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#7]
При переходе на экран с картой, затем вернутся на предыдущий экран и снова на экран карты, появляется ошибка, при удалении userLocationIcon={userLocation}, все норм. 

<img width="361" alt="Снимок экрана 2019-12-17 в 15 36 00" src="https://user-images.githubusercontent.com/20275419/70996101-2b0a9400-20e3-11ea-8c38-042b0bb1c1b3.png">

**Comment by ownikss** [comment]
Исправлено. Будет обновлено в версии 1.0.4 в течение недели
Сейчас можно получить код с этим фиксом из ветки v1.0.4, но ветка находится в разработке

**Comment by ownikss** [comment]
Исправлено в [версии 1.0.4](https://github.com/volga-volga/react-native-yamap/releases/tag/v1.0.4)
