### ISSUE TITLE
Не могу получить маршруты.

### ISSUE THREAD

**Issue by unLUCKYdude** [volga-volga/react-native-yamap#70]
Пробую использовать функцию findMasstransitRoutes, передав в неё массив, состоящий их двух точек ({ lat: number, lon: number }), а так же callback-функцию (e => console.log(e)). Данный коллбэк не отрабатывает.
Подскажите, пожалуйста, в чём может быть проблема?

**Comment by unLUCKYdude** [comment]
Я глянул файлы либы, а именно файл YamapView.java, и там есть функция:
public void findRoutes(ArrayList<Point> points, final ArrayList<String> vehicles, final String id) {}
которая пуста

**Comment by ownikss** [comment]
Добрый вечер, библиотека немного в подвешенном состоянии. Пока могу предложить несколько вариантов:

1. Попробуйте установить библиотеку с ветки feat/updateMarkers . В последней версии опубликована "light" версия библиотеки из-за жалоб на размер апк после обновления. В легкой версии только отображение карты и маркеров, а фрагмент с маршрутами не до конца почистили

2. Попробуйте установить предыдущую версию библиотеки (1.0.20). После этой версии были попытки с нашей стороны обновить sdk, но полноценно оттестировать все не удалось.

3. Попробуйте установить из форка https://github.com/EruditorGroup/react-native-yamap
У нас висит pull request из этого репозитория, но у нас нет возможности полноценно оттестировать функционал - сейчас у нас нет проектов с яндекс картами. Если вы отпишитесь что форк стабильно работает мы смержим его в наш репозиторий и выкатим как обновление

**Comment by unLUCKYdude** [comment]
К сожалению, не смог протестировать репозиторий из форка (ошибка при установке).
Решил установить версию 1.0.20. Всё работает.
Благодарю)

**Comment by ownikss** [comment]
Версию из форка смержил и выкатил как версию 4.0.0, чтобы соответствовать нативному sdk. Там действительно мажорные изменения и переезжать нужно осторожно
