### ISSUE TITLE
[Пожелание] Метод на получение гео позиции пользователя

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#72]
Возможно ли добавить метод, который возвращал бы гео данные пользователя, если его геолокация нам известна?

**Comment by unLUCKYdude** [comment]
Используйте библиотеку @react-native-community/geolocation.

**Comment by ownikss** [comment]
Yandex Mapkit действительно не отдает координаты пользователя - только отрисовывает их. Чтобы получить координаты можно воспользоваться другими средствами, например библиотекой выше
