### ISSUE TITLE
Ошибка при сборке архива 

### ISSUE THREAD

**Issue by StIch0** [volga-volga/react-native-yamap#77]
YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile, missing required architecture armv7 in file 

Xcode 13.0

**Comment by StIch0** [comment]
> Похожая проблема у меня тоже у iOS версий, с Android кое-как разобрался и запустился. А в iOS-е данная библиотека на симуляторе хорошо работает, но при сборке проекта происходить ошибка. Откатывался на старую версию библиотеки react-native-yamap, но не помогло и также убирал **armv7**.
> 
> ```
> react-native@0.63.4
> react-native-yamap@4.0.0
> ```
> 
> Прикрепил последний лог ошибки в картинке.
> 
> ![image](https://user-images.githubusercontent.com/84069292/138439131-f4e039f1-8a26-4393-96a2-bb617855de7b.png)

 "react-native-yamap": "^1.0.20",
 "react": "16.13.1",
 "react-native": "0.63.4",
 
 работает 
 попробуй почистить все и поставить заново

**Comment by ownikss** [comment]
В 4.1.6 проблема не наблюдается
