### ISSUE TITLE
Вылетает приложение

### ISSUE THREAD

**Issue by nmzgnv** [volga-volga/react-native-yamap#78]
При переключении между приложениями, мое вылетает. Ошибка связана с картой. Инициализацию делаю перед компонентом, как в документации.

![Screenshot_2021-09-30-00-00-11-132_com miui bugreport](https://user-images.githubusercontent.com/46592780/135332532-ab6be5b3-05ee-4e73-9cdb-3437ec907ab5.jpg)

**Comment by Yrsafam** [comment]
Вы прикрепите хоть код, где вы инициализируете и как.

**Comment by nmzgnv** [comment]
```
YaMap.init(yaMapAPIKey);
Geocoder.init(geocoderAPIKey);

const MapScreen = ({route, navigation}) => {
      ....
     <YaMap
          ref={map => {
            this.map = map;
          }}
          style={styles.map}
          showUserPosition={false}>
     .....
     </YaMap>
}
```
