### ISSUE TITLE
Фильтры для стилизации карты

### ISSUE THREAD

**Issue by alexdarh** [volga-volga/react-native-yamap#79]
Добрый день. Будут ли фильтры для стилизации карты. например:

.ymaps-layers-pane {
filter: grayscale(1);
-ms-filter: grayscale(1);
-webkit-filter: grayscale(1);
-moz-filter: grayscale(1);
-o-filter: grayscale(1);
}

**Comment by ch3rn1k** [comment]
Привет, можешь юзать стили на слой карт так:

```
<YaMap
  mapStyle={JSON.stringify([
    {
      stylers: {
        grayscale: 1
      }
    }
  ])}
/>
```

Больше в доках яндекса https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/style.html

**Comment by ch3rn1k** [comment]
@ownikss этот ишью тоже можно закрывать, функционал имеется
