### ISSUE TITLE
Back to map screen

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#8]
Когда возвращаешься на экран с картой, перестает работать клик на маркеры

**Comment by ownikss** [comment]
Можно более подробное описание проблемы?

Проверил сценарии:
- экран - переход к карте - назад - снова переход к карте
- экран - переход к карте - переход дальше - возврат к карте

Оба сценария отрабатывают корректно на обеих платформах

**Comment by ownikss** [comment]
@Azshar воспроизводится ли проблема на последней (**1.0.7**) версии библиотеки? в ней была полностью переработана логика маркеров

Можно закрывать issue?
