### ISSUE TITLE
Слишком быстрое движение карты при перемещении

### ISSUE THREAD

**Issue by DeducMe** [volga-volga/react-native-yamap#80]
https://ru.files.fm/f/fqnk56zhj
После передвижения карты - камера быстро перемещается
Начало происходить в новой версии и до этого не происходило.

`import YaMap from 'react-native-yamap';
import React, {useRef} from 'react';

export default function HomeScreen() {
  const map = useRef(null);

  return (
    <YaMap
      ref={map}
      // onMapPress={(event) => addNewMarker(event.nativeEvent)}

      style={{flex: 1, width: '100%', height: '100%'}}></YaMap>
  );
}
`

**Comment by dualism98** [comment]
Такая же проблема на iOS
Версия либы - 4.0.2

**Comment by Barney4242** [comment]
подтверждаю

**Comment by AlmiranteTim** [comment]
На ios до сих пор проблема актуальна.

**Comment by palindrom228** [comment]
Подскажите на что лучше откатиться?

**Comment by andreypaul** [comment]
Проблема всё ещё актуальна... неужели никто так и не решил?

**Comment by AlmiranteTim** [comment]
> Проблема всё ещё актуальна... неужели никто так и не решил?

Это проблема присутствует только на эмуляторе, на реальном устройстве все нормально.
