### ISSUE TITLE
Предложение: Добавить рисование полигона с помощью onMove

### ISSUE THREAD

**Issue by Anilead** [volga-volga/react-native-yamap#82]
Как я понимаю, нарисовать полигон на данный момент возможно только при нажатии на карту несколько раз. 

Хотелось бы добавить возможность рисования полигона по событию onTouchMove. Или получить координаты при вызове данного события.

Или я что-то упустил и уже сейчас можно таким способом нарисовать полигон?

**Comment by ownikss** [comment]
Новые пропсы добавлены в версии 4.1.5
