### ISSUE TITLE
Реализовать направление для маркера

### ISSUE THREAD

**Issue by alexdarh** [volga-volga/react-native-yamap#86]
Очень не хватает функции направления для маркера. 
Пытался рендерить маркеры как компоненты Image (через children) но у них не отрабатывает  style={{ transform: [{ rotate: "45deg" }]}} Очень не хватает функции )

**Comment by alexdarh** [comment]
Или посоветуйте как реализовать это не штатными методами )

**Comment by MoronovArt** [comment]
Делал похожую вещь через canvas

**Comment by ownikss** [comment]
Сейчас функционал не реализован, странно что через transform не работает

Нужно добавить возможность кастомизации стиля для элементов:
https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKIconStyle.html

Если кто-то готов сделать пулл реквест было бы отлично. Если нет - попробуем найти ресурсы на задачу.
Сама задача не сложная, если кто-то давно хотел попробовать нативный модуль - очень хороший способ начать

**Comment by ownikss** [comment]
Решали немного другую задачу, но косвенно затронули этот функционал

Стояла задача реализовать анимированный поворот маркера (машина при движении по карте). Через setState в js коде был бы слишком низкий fps, поэтому реализовали ref метод для маркера
```typescript
  public animatedRotateTo(angle: number, duration: number)
```
Для решения вашей задачи можно написать небольшую обертку и делать rotate в useEffect

```typescript
function MyMarker(props) {
  const {rotate, ...p} = props;
  const marker = useRef();
  useEffect(() => {
    if (marker.current) {
      // не уверен, что 0 отработает корректно, поэтому лучше использовать какое-то положительное число
      marker.current.animatedRotateTo(rotate, 10);
    }
  }, [rotate])
  return <Marker ref={marker} {...p} />
}
```
