### ISSUE TITLE
Не очищаются маркеры при подаче пустого массива в компонент

### ISSUE THREAD

**Issue by alexdarh** [volga-volga/react-native-yamap#87]
Добрый день. Скорее всего это моя ошибка, не ошибка react-native-yamap, но мало ли
![Снимок экрана 2021-11-23 182545](https://user-images.githubusercontent.com/62577345/143032230-35c60411-744c-4ab3-8c0b-926c32faa2e7.png)

Проблема в следующем, у меня есть карта в которой я рендерю маркеры путем map массива маркеров. Все маркеры выглядят как маленькие машинки. При наступлении события, массив маркеров обнуляется, (оставшаяся машинка показана другим маркером) и стейт cars становится равным [] но на картах почему-то остается один маркер в виде синей точки.

**Comment by nmzgnv** [comment]
Та же самая проблема

**Comment by youngblader** [comment]
Как вы отрисовали маршрут?

**Comment by youngblader** [comment]
> Добрый день. Скорее всего это моя ошибка, не ошибка react-native-yamap, но мало ли ![Снимок экрана 2021-11-23 182545](https://user-images.githubusercontent.com/62577345/143032230-35c60411-744c-4ab3-8c0b-926c32faa2e7.png)
> 
> Проблема в следующем, у меня есть карта в которой я рендерю маркеры путем map массива маркеров. Все маркеры выглядят как маленькие машинки. При наступлении события, массив маркеров обнуляется, (оставшаяся машинка показана другим маркером) и стейт cars становится равным [] но на картах почему-то остается один маркер в виде синей точки.

Подскажите, как вы отрисовали маршрут?

**Comment by alexdarh** [comment]
> Подскажите, как вы отрисовали маршрут?

Из маршрута [findDrivingRoutes(points: Point[], callback: (event: RoutesFoundEvent<DrivingInfo>) => void)] получил точки и по ним отрисовал Polyline

**Comment by youngblader** [comment]
> > Подскажите, как вы отрисовали маршрут?
> 
> Из маршрута [findDrivingRoutes(points: Point[], callback: (event: RoutesFoundEvent) => void)] получил точки и по ним отрисовал Polyline

А как вы вытянули точки? Можно пример?

**Comment by alexdarh** [comment]
> А как вы вытянули точки? Можно пример? map.current.findDrivingRoutes(points, event => console.log('event', event)) в свойствах ивента?

`YaMapRef.current.findDrivingRoutes(points, (event: any) => {
                    let route = event.nativeEvent.routes[0].sections
                    for (let i = 0; i < route.length; i++) {
                        polyline = polyline.concat(route[i].points);
                    }`
