### ISSUE TITLE
Invariant Violation requireNativeComponent AirMap was not found i UiManager

### ISSUE THREAD

**Issue by Azshar** [volga-volga/react-native-yamap#9]
На android ошибка Invariant Violation requireNativeComponent AirMap was not found i UiManager

**Comment by ownikss** [comment]
Я подозреваю что проблема не в этой библиотеке. AirMap используется в react-native-maps, если я правильно помню. Вероятно есть конфликты при использовании с react-native-maps или react-native-maps некорректно прилинкованы. Попробуйте убрать react-native-maps из зависимостей или хотя бы отключить для него autolinking. Если проблема останется напишите сюда, попробую посмотреть

**Comment by Azshar** [comment]
Да, clean & rebuild помог
