### ISSUE TITLE
Implement additional functionality for location determination 

### ISSUE THREAD

**Issue by MaKK99** [volga-volga/react-native-yamap#90]
Good afternoon!

I've been working with your library for a while and ran into the following problem:
When the user turns on the location function, their location is displayed on the map. But getting the X and Y coordinates of this place is impossible.

I propose to add such functionality. Obtaining these coordinates will track movements to determine if the user has reached the desired location.
Also, the ability to obtain coordinates will help in calculating the distance of the route from the user to the desired place on the route.

I believe this option is not limited to these capabilities, and other developers will also find useful use cases for this feature.

**Comment by alexdarh** [comment]
U can use  Geolocation.getCurrentPosition from react-native-geolocation-service

It success working both Android and iOS
