### ISSUE TITLE
Карта выходит за границы экрана (ios only)

### ISSUE THREAD

**Issue by byazamat** [volga-volga/react-native-yamap#97]
Здравствуйте, обнаружил не понятный баг с `YaMap` на **_IOS_**.

**Подробнее о баге:**
При первом открытии карты (То есть после первой инициализации: `YaMap.init("@API_KEY")`) карта открывается в нормальном виде:

![photo_2022-03-17_06-59-40](https://user-images.githubusercontent.com/77745661/158721557-9188c0f7-3826-4740-a9f0-d8936561d8c8.jpg)

Но уже при следующем входе в карту, она выходит за границы экрана (обратите внимание на логотип Яндекс):

![photo_2022-03-17_06-59-43](https://user-images.githubusercontent.com/77745661/158721553-793793df-4302-4ad4-9841-62a413b95425.jpg)

Пожалуйста объясните мне как мне решить эту проблему.

**Система:**
macOS: Monterey (12.1) M1
device: iPhone XR
react-native: 0.67.3
react-native-yamap: 4.0.3

**Comment by labtorie** [comment]
Тоже столкнулся с этой проблемой. В качестве костыля можно рендерить карту по таймауту, то есть немного позже, чем отрисуется View, внутри которой карта находится

**Comment by Wimmind** [comment]
@byazamat вопрос не по теме, но как ты установил рус язык?)
`YaMap.init('key');
YaMap.setLocale('ru').catch(e => console.error(e))`
инициализирую это в index.js перед компонентом, который регистрирую, но локаль не работает, также карта при зуме не показывает регионы/улицы/номера домов
что может быть не так?

**Comment by byazamat** [comment]
@Wimmind в моем случае, мне не нужно было устанавливать какой-то определенный язык.
Как я понимаю, Yandex карты сами определяют системный язык.

Как написано в документации может проблема с перезагрузкой приложения на Андроид:
> Для андроид изменение языка карт вступит в силу только после перезапуска приложения. См метод setLocale в документации нативного sdk. 

На счет того что не показывает регионы, может быть ты неправильно настроил саму карту в Yandex? Когда я использовал google maps, то там можно было настроить карту в консоли google очень гибко. Попробуй поковырять саму консоль Yandex.

Удачи)

**Comment by pioner92** [comment]
fixed
