### ISSUE TITLE
После обновления на Xcode 13.3 не собирается приложение

### ISSUE THREAD

**Issue by alexdarh** [volga-volga/react-native-yamap#98]
ld: in ....../ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file ...../ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode 13.3, в настройках проекта стоит excluded archs arm64.

**Comment by FonTain1991** [comment]
I confirm, me too

**Comment by yasinugrl** [comment]
me too also. Do you have any solition?

**Comment by alexdarh** [comment]
yes. downgrade Xcode to 12.3.1 ((

**Comment by yasinugrl** [comment]
@alexdarh  But As you know that after 15 april you will not archive your app from under of 13 version of xcode. How can we solved that problem?

**Comment by FonTain1991** [comment]
@yasinugrl explain about archiving?

**Comment by alexdarh** [comment]
@yasinugrl The Yandex mapKit developers some days ago was answer that thew will do support xcode 13 in library. But when it happens nobody dont know

**Comment by muratGursel** [comment]
Yandex mapkit updated 9 days ago, i try new change dependencies for yamap 4.0.0-full to 4.1.0 but not work properly its make another error when build time. Do you planned any update for Yamap

**Comment by Melber17** [comment]
similarly, need help  😥

**Comment by ownikss** [comment]
В 4.1.0 и выше проблема устранена
