### ISSUE TITLE
На android resetLocale крашит приложение.

### ISSUE THREAD

**Issue by Nafiar1991** [volga-volga/react-native-yamap#99]
Я понимаю, что много прошу. И все же. Просьба к автору обновить документацию и/или модуль. В нынешних реалиях модуль точно будет набирать популярность. Но все жалуются, что запустить его и заставить работать тот еще гемор.

**Comment by ch3rn1k** [comment]
С какой ошибкой вылет?

**Comment by ownikss** [comment]
на текущий момент было много исправлений в том числе связанных с локализацией. В 4.1.6 должно быть исправлено
